plugins:
  - babel
  - jest
env:
  node: true
  jest: true
  browser: true
  commonjs: true

parser: babel-eslint
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
rules:
  no-console: 0
  indent: [2, 2]
  no-shadow: off
